# Generated by Django 5.2.13 on 2026-05-09 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('strategy', 'Strategy decision'), ('recruiter', 'Recruiter comment'), ('interview', 'Interview learning'), ('cv_change', 'CV / profile change'), ('role_targeting', 'Role targeting'), ('blocker', 'Blocker'), ('lesson', 'Lesson learned'), ('general', 'General note')], default='general', max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=240)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-is_important', '-decision_date', '-created_at'],
            },
        ),
    ]
