# Generated by Django 5.2.13 on 2026-05-21 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0003_alter_jobapplication_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('sender_name', models.CharField(blank=True, max_length=160)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField()),
                ('date_received', models.DateTimeField()),
                ('email_type', models.CharField(choices=[('unknown', 'Unknown'), ('acknowledgement', 'Application Acknowledgement'), ('interest', 'Recruiter Interest'), ('new_opportunity', 'New Opportunity'), ('availability_request', 'Availability Request'), ('screening_invite', 'Screening Call Invite'), ('interview_invite', 'Interview Invite'), ('reschedule_or_cancellation', 'Reschedule or Cancellation'), ('task_or_test', 'Task or Test Request'), ('cv_request', 'CV or Portfolio Request'), ('document_request', 'Document Request'), ('salary_question', 'Salary Question'), ('right_to_work_question', 'Right-to-Work Question'), ('location_work_mode_question', 'Location or Work Mode Question'), ('rejection', 'Rejection'), ('role_closed_or_on_hold', 'Role Closed or On Hold'), ('offer_or_next_steps', 'Offer or Next Steps'), ('other', 'Other')], default='unknown', max_length=40)),
                ('matched_signals', models.TextField(blank=True)),
                ('classification_rationale', models.CharField(blank=True, max_length=300)),
                ('reply_draft', models.TextField(blank=True)),
                ('reply_status', models.CharField(choices=[('drafted', 'Draft ready'), ('needs_review', 'Needs review'), ('not_required', 'No reply required'), ('sent_manually', 'Sent manually'), ('archived', 'Archived')], default='needs_review', max_length=20)),
                ('requires_reply', models.BooleanField(default=True)),
                ('action_due_at', models.DateTimeField(blank=True, null=True)),
                ('suggested_application_status', models.CharField(blank=True, max_length=40)),
                ('import_source', models.CharField(choices=[('manual', 'Manual paste'), ('gmail', 'Gmail API import')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_emails', to='applications.jobapplication')),
            ],
            options={
                'verbose_name': 'Recruiter email',
                'verbose_name_plural': 'Recruiter emails',
                'ordering': ['-date_received', '-created_at'],
            },
        ),
    ]
