# Generated by Django 5.2.13 on 2026-05-09 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('target_applications', models.PositiveIntegerField(default=0)),
                ('actual_applications', models.PositiveIntegerField(default=0)),
                ('cover_letters_drafted', models.PositiveIntegerField(default=0)),
                ('responses_received', models.PositiveIntegerField(default=0)),
                ('calls_received', models.PositiveIntegerField(default=0)),
                ('hours_spent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('energy_level', models.PositiveSmallIntegerField(default=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily log',
                'verbose_name_plural': 'Daily logs',
                'ordering': ['-log_date'],
                'unique_together': {('user', 'log_date')},
            },
        ),
    ]
