import io
import os
import unittest
from contextlib import redirect_stderr, redirect_stdout
from unittest import mock

from scripts import notion_sync_career_evidence as notion_sync
from scripts.notion_sync_career_evidence import (
    API_KEY_ENV,
    DATABASE_ID_ENV,
    EVIDENCE_DEFINITIONS,
    EXPECTED_RECORD_NAMES,
    NOTION_PROPERTY_NAMES,
    EnvValidationError,
    EvidenceMetadata,
    PlannedAction,
    build_metadata,
    build_metadata_records,
    build_notion_properties,
    format_planned_record_lines,
    plan_sync_actions,
    print_planned_actions,
    run_sync,
    validate_env,
)


class NotionSyncEnvValidationTests(unittest.TestCase):
    def test_validate_env_detects_missing_api_key(self):
        env = {DATABASE_ID_ENV: "db-123"}
        with mock.patch.dict(os.environ, env, clear=True):
            with self.assertRaises(EnvValidationError) as ctx:
                validate_env(require_credentials=True)
        self.assertIn(API_KEY_ENV, str(ctx.exception))
        self.assertNotIn("your_notion_api_key", str(ctx.exception))

    def test_validate_env_detects_missing_database_id(self):
        env = {API_KEY_ENV: "secret-test-key"}
        with mock.patch.dict(os.environ, env, clear=True):
            with self.assertRaises(EnvValidationError) as ctx:
                validate_env(require_credentials=True)
        self.assertIn(DATABASE_ID_ENV, str(ctx.exception))

    def test_validate_env_accepts_both_variables(self):
        env = {
            API_KEY_ENV: "secret-test-key",
            DATABASE_ID_ENV: "db-123",
        }
        with mock.patch.dict(os.environ, env, clear=True):
            api_key, database_id = validate_env(require_credentials=True)
        self.assertEqual(api_key, "secret-test-key")
        self.assertEqual(database_id, "db-123")

    def test_validate_env_allows_missing_variables_when_not_required(self):
        with mock.patch.dict(os.environ, {}, clear=True):
            api_key, database_id = validate_env(require_credentials=False)
        self.assertEqual(api_key, "")
        self.assertEqual(database_id, "")


class NotionSyncRecordConfigTests(unittest.TestCase):
    def test_evidence_definitions_define_six_expected_names(self):
        names = [definition.name for definition in EVIDENCE_DEFINITIONS]
        self.assertEqual(names, list(EXPECTED_RECORD_NAMES))
        self.assertEqual(len(EXPECTED_RECORD_NAMES), 6)

    def test_metadata_records_include_all_expected_names(self):
        records = build_metadata_records()
        self.assertEqual([record.name for record in records], list(EXPECTED_RECORD_NAMES))

    def test_playwright_record_marks_screenshot_ready_when_pngs_exist(self):
        screenshots = EVIDENCE_DEFINITIONS[4]
        metadata = build_metadata(screenshots)
        self.assertTrue(metadata.screenshot_ready)
        self.assertEqual(metadata.status, "Ready")

    def test_path_status_reports_in_progress_for_partial_paths(self):
        existing = mock.Mock()
        existing.exists.return_value = True
        missing = mock.Mock()
        missing.exists.return_value = False
        status = notion_sync.path_status([existing, missing])
        self.assertEqual(status, "In Progress")

    def test_path_status_reports_missing_when_no_paths_exist(self):
        missing = mock.Mock()
        missing.exists.return_value = False
        status = notion_sync.path_status([missing])
        self.assertEqual(status, "Missing")


class NotionSyncPayloadTests(unittest.TestCase):
    def test_payload_contains_required_notion_fields(self):
        metadata = build_metadata(EVIDENCE_DEFINITIONS[0])
        properties = build_notion_properties(metadata)
        self.assertEqual(set(properties.keys()), set(NOTION_PROPERTY_NAMES))

    def test_payload_maps_metadata_values(self):
        metadata = EvidenceMetadata(
            name="Project Evidence Report",
            category="Markdown Evidence",
            status="Ready",
            sprint="Sprint 23A (V1)",
            git_tag="sprint-23e-complete",
            screenshot_ready=False,
            last_updated="2026-05-19",
            local_path="docs/career_evidence/01_project_evidence_report.md",
            notes="Generated by tools/career_evidence_audit.py",
        )
        properties = build_notion_properties(metadata)

        self.assertEqual(
            properties["Name"]["title"][0]["text"]["content"],
            "Project Evidence Report",
        )
        self.assertEqual(properties["Category"]["select"]["name"], "Markdown Evidence")
        self.assertEqual(properties["Status"]["select"]["name"], "Ready")
        self.assertEqual(
            properties["Sprint"]["rich_text"][0]["text"]["content"],
            "Sprint 23A (V1)",
        )
        self.assertEqual(
            properties["Git Tag"]["rich_text"][0]["text"]["content"],
            "sprint-23e-complete",
        )
        self.assertFalse(properties["Screenshot Ready"]["checkbox"])
        self.assertEqual(
            properties["Local Path"]["rich_text"][0]["text"]["content"],
            "docs/career_evidence/01_project_evidence_report.md",
        )
        self.assertEqual(properties["Last Updated"]["date"]["start"], "2026-05-19")


class NotionSyncDryRunTests(unittest.TestCase):
    def test_format_planned_record_lines_include_required_fields(self):
        metadata = build_metadata(EVIDENCE_DEFINITIONS[0])
        lines = format_planned_record_lines(metadata, action="create", dry_run=True)
        joined = "\n".join(lines)
        for label in (
            "Name:",
            "Status:",
            "Category:",
            "Sprint:",
            "Git Tag:",
            "Screenshot Ready:",
            "Local Path:",
        ):
            with self.subTest(label=label):
                self.assertIn(label, joined)
        self.assertIn(metadata.name, joined)
        self.assertIn(metadata.status, joined)
        self.assertIn(metadata.local_path, joined)

    def test_print_planned_actions_outputs_clear_dry_run_summary(self):
        metadata = build_metadata(EVIDENCE_DEFINITIONS[0])
        actions = [
            PlannedAction(action="create", name=metadata.name, metadata=metadata),
        ]
        buffer = io.StringIO()
        with redirect_stdout(buffer):
            print_planned_actions(actions, dry_run=True)
        output = buffer.getvalue()
        self.assertIn("[DRY-RUN]", output)
        self.assertIn("Name:", output)
        self.assertIn("Status:", output)
        self.assertIn("Category:", output)
        self.assertIn("Sprint:", output)
        self.assertIn("Git Tag:", output)
        self.assertIn("Screenshot Ready:", output)
        self.assertIn("Local Path:", output)
        self.assertIn(metadata.name, output)

    def test_dry_run_does_not_require_credentials(self):
        with mock.patch.dict(os.environ, {}, clear=True):
            exit_code = run_sync(dry_run=True)
        self.assertEqual(exit_code, 0)

    def test_dry_run_does_not_instantiate_notion_client(self):
        with mock.patch.dict(os.environ, {}, clear=True):
            with mock.patch.object(notion_sync, "NotionSyncClient") as client_cls:
                run_sync(dry_run=True)
        client_cls.assert_not_called()

    def test_dry_run_does_not_call_requests_session(self):
        with mock.patch.dict(os.environ, {}, clear=True):
            with mock.patch.object(notion_sync.requests, "Session") as session_cls:
                run_sync(dry_run=True)
        session_cls.assert_not_called()


class NotionSyncPlanningTests(unittest.TestCase):
    def test_plan_sync_actions_update_when_name_exists(self):
        records = build_metadata_records()
        existing = {records[0].name: {"id": "page-abc", "properties": {}}}
        planned = plan_sync_actions(records, existing)
        self.assertEqual(planned[0].action, "update")
        self.assertEqual(planned[0].page_id, "page-abc")
        self.assertEqual(planned[1].action, "create")

    def test_plan_sync_actions_create_when_name_missing(self):
        metadata = build_metadata(EVIDENCE_DEFINITIONS[0])
        planned = plan_sync_actions([metadata], {})
        self.assertEqual(len(planned), 1)
        self.assertEqual(planned[0].action, "create")
        self.assertIsNone(planned[0].page_id)


class NotionSyncLiveModeGuardTests(unittest.TestCase):
    def test_live_mode_requires_credentials(self):
        stderr = io.StringIO()
        with mock.patch.dict(os.environ, {}, clear=True):
            with redirect_stderr(stderr):
                exit_code = run_sync(dry_run=False)
        self.assertEqual(exit_code, 1)
        self.assertIn(API_KEY_ENV, stderr.getvalue())

    def test_live_mode_does_not_call_api_when_credentials_missing(self):
        stderr = io.StringIO()
        with mock.patch.dict(os.environ, {}, clear=True):
            with redirect_stderr(stderr):
                with mock.patch.object(notion_sync, "NotionSyncClient") as client_cls:
                    with mock.patch.object(notion_sync.requests, "Session") as session_cls:
                        run_sync(dry_run=False)
        client_cls.assert_not_called()
        session_cls.assert_not_called()


if __name__ == "__main__":
    unittest.main()
