# Generated by Django 5.2.13 on 2026-05-25 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0003_alter_jobapplication_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('application', 'Application'), ('screening', 'Screening'), ('technical', 'Technical'), ('interview', 'Interview')], max_length=40)),
                ('skill_name', models.CharField(max_length=120)),
                ('current_tier', models.CharField(choices=[('missing', 'Missing'), ('emerging', 'Emerging'), ('practicing', 'Practicing'), ('demonstrated', 'Demonstrated')], max_length=40)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('goal_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('stage_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('priority_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('jd_requirement', models.TextField(blank=True)),
                ('identified_by', models.CharField(choices=[('manual', 'Manual review'), ('rule_based', 'Rule-based review'), ('self_review', 'Self review')], default='manual', max_length=40)),
                ('suggested_action', models.TextField(blank=True)),
                ('long_term_goal', models.CharField(choices=[('data_analyst', 'Data Analyst'), ('bi_analyst', 'BI Analyst'), ('analytics_engineer', 'Analytics Engineer'), ('data_engineer', 'Data Engineer'), ('general', 'General')], default='general', max_length=40)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('resolved_tier', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='applications.jobapplication')),
            ],
            options={
                'verbose_name': 'Application skill gap',
                'verbose_name_plural': 'Application skill gaps',
                'ordering': ['-priority_score', '-updated_at'],
                'indexes': [models.Index(fields=['application'], name='skill_gap_application_idx'), models.Index(fields=['stage'], name='skill_gap_stage_idx'), models.Index(fields=['priority'], name='skill_gap_priority_idx'), models.Index(fields=['skill_name'], name='skill_gap_skill_name_idx'), models.Index(fields=['resolved'], name='skill_gap_resolved_idx')],
                'constraints': [models.UniqueConstraint(fields=('application', 'skill_name', 'stage'), name='uniq_application_skill_gap_stage')],
            },
        ),
    ]
