# Generated by Django 5.2.13 on 2026-08-07 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_gaps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplanationRequestCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_date', models.DateField()),
                ('request_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanation_request_counters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Explanation request counter',
                'verbose_name_plural': 'Explanation request counters',
                'constraints': [models.UniqueConstraint(fields=('user', 'window_date'), name='uniq_explanation_request_counter_user_date'), models.CheckConstraint(condition=models.Q(('request_count__gte', 1)), name='chk_explanation_request_counter_count_gte_1')],
            },
        ),
    ]
