# Generated by Django 5.2.1 on 2026-06-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkillEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("data_engineering", "Data Engineering"),
                            ("analytics_engineering", "Analytics Engineering"),
                            ("business_intelligence", "Business Intelligence"),
                            ("programming", "Programming"),
                            ("cloud", "Cloud Platform"),
                            ("governance", "Data Governance / AI Governance"),
                            ("domain", "Domain Knowledge"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=100,
                    ),
                ),
                (
                    "evidence_level",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "Verified - portfolio evidence confirmed"),
                            (
                                "LEARNING_TARGET",
                                "Learning Target - developing, not yet evidenced",
                            ),
                            ("STUDYING", "Studying - personal study only"),
                            (
                                "NO_EVIDENCE",
                                "No Evidence - gap identified, not yet started",
                            ),
                        ],
                        default="NO_EVIDENCE",
                        max_length=30,
                    ),
                ),
                ("sprint_reference", models.CharField(blank=True, max_length=100)),
                ("project_link", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Skill Entry",
                "verbose_name_plural": "Skill Entries",
            },
        ),
    ]
