# Generated by Django 5.2.13 on 2026-05-09 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=160)),
                ('job_title', models.CharField(max_length=180)),
                ('job_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('work_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('flexible', 'Flexible'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('salary_range', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('welcome_to_the_jungle', 'Welcome to the Jungle'), ('company_website', 'Company website'), ('recruiter', 'Recruiter'), ('referral', 'Referral'), ('other', 'Other')], default='other', max_length=40)),
                ('role_fit', models.CharField(choices=[('strong', 'Strong fit'), ('medium', 'Medium fit'), ('weak', 'Weak fit'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('date_applied', models.DateField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('auto_rejected', 'Auto-rejected'), ('no_response', 'No response'), ('acknowledged', 'Acknowledged'), ('screening_call', 'Screening call'), ('technical_screen', 'Technical screen'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrew', 'Withdrew')], default='submitted', max_length=40)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('cv_version', models.CharField(blank=True, max_length=120)),
                ('cover_letter_version', models.CharField(blank=True, max_length=120)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job application',
                'verbose_name_plural': 'Job applications',
                'ordering': ['-date_applied', '-created_at'],
            },
        ),
    ]
