# Generated by Django 5.2.13 on 2026-05-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company_researched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience_level',
            field=models.CharField(blank=True, help_text='Example: graduate, junior, 0-2 years, 3+ years', max_length=120),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='follow_up_status',
            field=models.CharField(choices=[('not_set', 'Not set'), ('not_due', 'Not due'), ('due', 'Due'), ('sent', 'Sent'), ('responded', 'Responded'), ('not_needed', 'Not needed')], default='not_set', max_length=30),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_cover_letter_tailored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_cv_tailored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_description',
            field=models.TextField(blank=True, help_text='Optional short job description or copied requirements.'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='last_contacted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='next_action',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='pipeline_stage',
            field=models.CharField(choices=[('job_found', 'Job found'), ('fit_checked', 'Fit checked'), ('cv_selected', 'CV selected'), ('cover_letter_drafted', 'Cover letter drafted'), ('submitted', 'Application submitted'), ('follow_up_due', 'Follow-up due'), ('recruiter_responded', 'Recruiter responded'), ('screening_call', 'Screening call'), ('technical_task', 'Technical / task stage'), ('interview', 'Interview'), ('final_interview', 'Final interview'), ('closed', 'Closed')], default='job_found', max_length=40),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='portfolio_project_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Paste key skills from the job description.'),
        ),
    ]
