# Generated by Django 5.2.13 on 2026-05-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_jobapplication_company_researched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(choices=[('reed', 'Reed.co.uk'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('welcome_to_the_jungle', 'Welcome to the Jungle'), ('company_website', 'Company Website'), ('recruiter', 'Recruiter'), ('referral', 'Referral'), ('bookmarklet', 'Bookmarklet'), ('other', 'Other')], default='other', max_length=40),
        ),
    ]
