# Generated by Django 5.2.10 on 2026-05-30 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_jobapplication_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cv', 'CV'), ('cover_letter', 'Cover letter')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('submitted', 'Submitted'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('job_analyzer', 'Job analyzer'), ('master_cv_baseline', 'Master CV baseline')], default='manual', max_length=30)),
                ('content', models.TextField(blank=True)),
                ('tailoring_notes', models.TextField(blank=True)),
                ('project_evidence', models.TextField(blank=True)),
                ('claim_safety_notes', models.TextField(blank=True)),
                ('quick_call_notes', models.TextField(blank=True)),
                ('cv_baseline_name', models.CharField(blank=True, default='Aminul_Islam_Data_Analyst_CV', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.jobapplication')),
            ],
            options={
                'verbose_name': 'Application document',
                'verbose_name_plural': 'Application documents',
                'ordering': ['application', 'document_type', 'name'],
            },
        ),
    ]
