# Generated by Django 5.2.10 on 2026-05-30 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_applicationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='selected_cover_letter_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_as_cover_letter_for_applications', to='applications.applicationdocument'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='selected_cv_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_as_cv_for_applications', to='applications.applicationdocument'),
        ),
    ]
