# Generated by Django 5.2.10 on 2026-05-31 19:02

import apps.applications.models
import apps.applications.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_jobapplication_selected_cover_letter_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='uploaded_file',
            field=models.FileField(blank=True, storage=apps.applications.storage.UploadedApplicationDocumentStorage(), upload_to=apps.applications.models.application_document_upload_to),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('job_analyzer', 'Job analyzer'), ('master_cv_baseline', 'Master CV baseline'), ('user_upload', 'User uploaded')], default='manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('ready_for_manual_submission', 'Ready for manual submission'), ('submitted', 'Submitted'), ('archived', 'Archived')], default='draft', max_length=40),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='pipeline_stage',
            field=models.CharField(choices=[('saved_for_later', 'Saved for later'), ('job_found', 'Job found'), ('fit_checked', 'Fit checked'), ('cv_selected', 'CV selected'), ('cover_letter_drafted', 'Cover letter drafted'), ('submitted', 'Application submitted'), ('follow_up_due', 'Follow-up due'), ('recruiter_responded', 'Recruiter responded'), ('screening_call', 'Screening call'), ('technical_task', 'Technical / task stage'), ('interview', 'Interview'), ('final_interview', 'Final interview'), ('closed', 'Closed')], default='job_found', max_length=40),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('saved_for_later', 'Saved for later'), ('submitted', 'Submitted'), ('auto_rejected', 'Auto-rejected'), ('no_response', 'No response'), ('acknowledged', 'Acknowledged'), ('screening_call', 'Screening call'), ('technical_screen', 'Technical screen'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrew', 'Withdrew')], default='submitted', max_length=40),
        ),
    ]
