# Generated by Django 5.2 on 2026-06-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_applicationdocument_upload_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('job_analyzer', 'Job analyzer'), ('master_cv_baseline', 'Master CV baseline'), ('user_upload', 'User uploaded'), ('external_reference', 'External reference')], default='manual', max_length=30),
        ),
    ]
