"""Sync Career Evidence metadata/status to a Notion database (optional tooling)."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import requests

REPO_ROOT = Path(__file__).resolve().parent.parent
EVIDENCE_DOCS_DIR = REPO_ROOT / "docs" / "career_evidence"
SCREENSHOTS_DIR = REPO_ROOT / "docs" / "screenshots" / "career_evidence"
NOTION_DOCS_DIR = REPO_ROOT / "docs" / "notion"

API_KEY_ENV = "NOTION_API_KEY"
DATABASE_ID_ENV = "NOTION_DATABASE_ID"
NOTION_API_BASE = "https://api.notion.com/v1"
NOTION_VERSION = "2022-06-28"
REQUEST_TIMEOUT_SECONDS = 30

GIT_NOT_AVAILABLE = "n/a"

EXPECTED_RECORD_NAMES: tuple[str, ...] = (
    "Project Evidence Report",
    "Job-Fit Matrix",
    "Recruiter Evidence Pack",
    "Career Evidence Dashboard UI",
    "Playwright Screenshots",
    "Notion Sync",
)

NOTION_PROPERTY_NAMES: tuple[str, ...] = (
    "Name",
    "Category",
    "Status",
    "Sprint",
    "Git Tag",
    "Screenshot Ready",
    "Last Updated",
    "Local Path",
    "Notes",
)

SCREENSHOT_FILES: tuple[str, ...] = (
    "career_evidence_overview.png",
    "project_evidence_report.png",
    "job_fit_matrix.png",
    "recruiter_pack.png",
)


class EnvValidationError(RuntimeError):
    """Raised when required Notion environment variables are missing."""


@dataclass(frozen=True)
class EvidenceDefinition:
    name: str
    category: str
    sprint: str
    local_paths: tuple[str, ...]
    notes: str = ""
    requires_screenshots: bool = False


EVIDENCE_DEFINITIONS: tuple[EvidenceDefinition, ...] = (
    EvidenceDefinition(
        name="Project Evidence Report",
        category="Markdown Evidence",
        sprint="Sprint 23A (V1)",
        local_paths=("docs/career_evidence/01_project_evidence_report.md",),
        notes="Generated by tools/career_evidence_audit.py",
    ),
    EvidenceDefinition(
        name="Job-Fit Matrix",
        category="Markdown Evidence",
        sprint="Sprint 23B (V2)",
        local_paths=("docs/career_evidence/02_job_fit_matrix.md",),
        notes="Generated by tools/career_job_fit_matrix.py",
    ),
    EvidenceDefinition(
        name="Recruiter Evidence Pack",
        category="Markdown Evidence",
        sprint="Sprint 23C (V3)",
        local_paths=("docs/career_evidence/03_recruiter_evidence_pack.md",),
        notes="Generated by tools/career_recruiter_pack.py",
    ),
    EvidenceDefinition(
        name="Career Evidence Dashboard UI",
        category="Dashboard",
        sprint="Sprint 23D (V4)",
        local_paths=(
            "apps/dashboard/views/career_evidence_views.py",
            "templates/dashboard/career_evidence/index.html",
        ),
        notes="Read-only Django dashboard viewer for V1-V3 markdown.",
    ),
    EvidenceDefinition(
        name="Playwright Screenshots",
        category="Screenshots",
        sprint="Sprint 23E (V5)",
        local_paths=tuple(
            f"docs/screenshots/career_evidence/{filename}" for filename in SCREENSHOT_FILES
        ),
        notes="Captured by scripts/capture_career_evidence_screenshots.py",
        requires_screenshots=True,
    ),
    EvidenceDefinition(
        name="Notion Sync",
        category="Sync",
        sprint="Sprint 23F (V6)",
        local_paths=(
            "scripts/notion_sync_career_evidence.py",
            "docs/notion/README.md",
        ),
        notes="Metadata/status sync only; no markdown or binary uploads.",
    ),
)


@dataclass
class EvidenceMetadata:
    name: str
    category: str
    status: str
    sprint: str
    git_tag: str
    screenshot_ready: bool
    last_updated: str | None
    local_path: str
    notes: str


@dataclass
class PlannedAction:
    action: str
    name: str
    page_id: str | None = None
    metadata: EvidenceMetadata | None = None


def _run_git(args: list[str]) -> str | None:
    try:
        completed = subprocess.run(
            ["git", *args],
            cwd=REPO_ROOT,
            check=False,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, OSError):
        return None
    if completed.returncode != 0:
        return None
    return completed.stdout.rstrip("\n")


def collect_git_tag() -> str:
    tag = _run_git(["describe", "--tags", "--abbrev=0"])
    if tag:
        return tag
    tags = _run_git(["tag", "--sort=-creatordate"])
    if tags:
        first = tags.splitlines()[0].strip()
        if first:
            return first
    return GIT_NOT_AVAILABLE


def collect_git_branch() -> str:
    branch = _run_git(["rev-parse", "--abbrev-ref", "HEAD"])
    return branch or GIT_NOT_AVAILABLE


def resolve_paths(definition: EvidenceDefinition) -> list[Path]:
    return [REPO_ROOT / relative for relative in definition.local_paths]


def path_status(paths: list[Path]) -> str:
    if not paths:
        return "Missing"
    existing = [path for path in paths if path.exists()]
    if len(existing) == len(paths):
        return "Ready"
    if existing:
        return "In Progress"
    return "Missing"


def latest_mtime_iso(paths: list[Path]) -> str | None:
    timestamps = [path.stat().st_mtime for path in paths if path.exists()]
    if not timestamps:
        return None
    updated = datetime.fromtimestamp(max(timestamps), tz=UTC)
    return updated.date().isoformat()


def local_path_display(definition: EvidenceDefinition, paths: list[Path]) -> str:
    existing = [path for path in paths if path.exists()]
    if not existing:
        return "; ".join(definition.local_paths)
    return "; ".join(_relative(path) for path in existing)


def _relative(path: Path) -> str:
    try:
        return path.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def screenshot_ready(definition: EvidenceDefinition, paths: list[Path]) -> bool:
    if definition.requires_screenshots:
        return bool(paths) and all(path.exists() for path in paths)
    return any(path.suffix.lower() == ".png" and path.exists() for path in paths)


def build_metadata(definition: EvidenceDefinition) -> EvidenceMetadata:
    paths = resolve_paths(definition)
    status = path_status(paths)
    return EvidenceMetadata(
        name=definition.name,
        category=definition.category,
        status=status,
        sprint=definition.sprint,
        git_tag=collect_git_tag(),
        screenshot_ready=screenshot_ready(definition, paths),
        last_updated=latest_mtime_iso(paths),
        local_path=local_path_display(definition, paths),
        notes=definition.notes,
    )


def build_metadata_records() -> list[EvidenceMetadata]:
    return [build_metadata(definition) for definition in EVIDENCE_DEFINITIONS]


def validate_env(*, require_credentials: bool) -> tuple[str, str]:
    api_key = os.environ.get(API_KEY_ENV, "").strip()
    database_id = os.environ.get(DATABASE_ID_ENV, "").strip()
    if not require_credentials:
        return api_key, database_id
    missing = []
    if not api_key:
        missing.append(API_KEY_ENV)
    if not database_id:
        missing.append(DATABASE_ID_ENV)
    if missing:
        raise EnvValidationError(
            "Missing required environment variables: "
            + ", ".join(missing)
            + "\nSee docs/notion/README.md and docs/notion/notion_sync_example.env"
        )
    return api_key, database_id


def rich_text(content: str) -> dict[str, Any]:
    return {
        "rich_text": [
            {
                "type": "text",
                "text": {"content": content[:2000]},
            }
        ]
    }


def build_notion_properties(metadata: EvidenceMetadata) -> dict[str, Any]:
    properties: dict[str, Any] = {
        "Name": {
            "title": [
                {
                    "type": "text",
                    "text": {"content": metadata.name},
                }
            ]
        },
        "Category": {"select": {"name": metadata.category}},
        "Status": {"select": {"name": metadata.status}},
        "Sprint": rich_text(metadata.sprint),
        "Git Tag": rich_text(metadata.git_tag),
        "Screenshot Ready": {"checkbox": metadata.screenshot_ready},
        "Local Path": rich_text(metadata.local_path),
        "Notes": rich_text(metadata.notes),
    }
    properties["Last Updated"] = (
        {"date": {"start": metadata.last_updated}}
        if metadata.last_updated
        else {"date": None}
    )
    return properties


def extract_page_name(page: dict[str, Any]) -> str:
    properties = page.get("properties", {})
    name_property = properties.get("Name") or properties.get("name")
    if not name_property or name_property.get("type") != "title":
        return ""
    return "".join(item.get("plain_text", "") for item in name_property.get("title", []))


class NotionSyncClient:
    def __init__(self, api_key: str, database_id: str) -> None:
        self.database_id = database_id
        self.session = requests.Session()
        self.session.headers.update(
            {
                "Authorization": f"Bearer {api_key}",
                "Notion-Version": NOTION_VERSION,
                "Content-Type": "application/json",
            }
        )

    def _request(
        self,
        method: str,
        path: str,
        payload: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        url = f"{NOTION_API_BASE}{path}"
        response = self.session.request(
            method,
            url,
            json=payload,
            timeout=REQUEST_TIMEOUT_SECONDS,
        )
        if response.status_code >= 400:
            detail = response.text.strip()
            if len(detail) > 300:
                detail = detail[:300] + "..."
            raise RuntimeError(f"Notion API {response.status_code}: {detail}")
        if not response.content:
            return {}
        return response.json()

    def query_database_pages(self) -> list[dict[str, Any]]:
        pages: list[dict[str, Any]] = []
        payload: dict[str, Any] = {}
        while True:
            data = self._request(
                "POST",
                f"/databases/{self.database_id}/query",
                payload,
            )
            pages.extend(data.get("results", []))
            if not data.get("has_more"):
                break
            payload = {"start_cursor": data["next_cursor"]}
        return pages

    def create_page(self, metadata: EvidenceMetadata) -> dict[str, Any]:
        payload = {
            "parent": {"database_id": self.database_id},
            "properties": build_notion_properties(metadata),
        }
        return self._request("POST", "/pages", payload)

    def update_page(self, page_id: str, metadata: EvidenceMetadata) -> dict[str, Any]:
        payload = {"properties": build_notion_properties(metadata)}
        return self._request("PATCH", f"/pages/{page_id}", payload)


def index_pages_by_name(pages: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    indexed: dict[str, dict[str, Any]] = {}
    for page in pages:
        name = extract_page_name(page)
        if name and name not in indexed:
            indexed[name] = page
    return indexed


def plan_sync_actions(
    metadata_records: list[EvidenceMetadata],
    existing_pages: dict[str, dict[str, Any]],
) -> list[PlannedAction]:
    planned: list[PlannedAction] = []
    for metadata in metadata_records:
        existing = existing_pages.get(metadata.name)
        if existing:
            planned.append(
                PlannedAction(
                    action="update",
                    name=metadata.name,
                    page_id=existing.get("id"),
                    metadata=metadata,
                )
            )
        else:
            planned.append(
                PlannedAction(
                    action="create",
                    name=metadata.name,
                    metadata=metadata,
                )
            )
    return planned


def format_screenshot_ready(metadata: EvidenceMetadata) -> str:
    return "Yes" if metadata.screenshot_ready else "No"


def format_planned_action_label(action: str, *, dry_run: bool) -> str:
    verb = action.upper()
    if dry_run and verb == "CREATE":
        return (
            f"{verb} (dry-run preview; live sync uses UPDATE when Name already exists)"
        )
    if verb == "UPDATE":
        return verb
    return verb


def format_planned_record_lines(
    metadata: EvidenceMetadata,
    *,
    action: str,
    dry_run: bool,
    page_id: str | None = None,
) -> list[str]:
    lines = [
        f"  Planned action:    {format_planned_action_label(action, dry_run=dry_run)}",
        f"  Name:              {metadata.name}",
        f"  Status:            {metadata.status}",
        f"  Category:          {metadata.category}",
        f"  Sprint:            {metadata.sprint}",
        f"  Git Tag:           {metadata.git_tag}",
        f"  Screenshot Ready:  {format_screenshot_ready(metadata)}",
        f"  Local Path:        {metadata.local_path}",
    ]
    if page_id:
        lines.append(f"  Notion page id:    {page_id}")
    if metadata.last_updated:
        lines.append(f"  Last Updated:      {metadata.last_updated}")
    if metadata.notes:
        lines.append(f"  Notes:             {metadata.notes}")
    return lines


def print_planned_actions(actions: list[PlannedAction], *, dry_run: bool) -> None:
    mode = "DRY-RUN" if dry_run else "LIVE"
    print(f"[{mode}] Planned sync for {len(actions)} record(s).")
    if dry_run:
        print("No Notion API calls will be made.")
    print()

    for index, item in enumerate(actions, start=1):
        metadata = item.metadata
        if metadata is None:
            print(f"[{mode}] Record {index}/{len(actions)}: {item.name} (no metadata)")
            print()
            continue

        print(f"[{mode}] Record {index}/{len(actions)}")
        for line in format_planned_record_lines(
            metadata,
            action=item.action,
            dry_run=dry_run,
            page_id=item.page_id,
        ):
            print(line)
        print()


def execute_sync(client: NotionSyncClient, actions: list[PlannedAction]) -> tuple[int, int]:
    created = 0
    updated = 0
    failures: list[str] = []

    for item in actions:
        if item.metadata is None:
            continue
        try:
            if item.action == "update" and item.page_id:
                client.update_page(item.page_id, item.metadata)
                updated += 1
                print(f"Updated: {item.name}")
            else:
                client.create_page(item.metadata)
                created += 1
                print(f"Created: {item.name}")
        except Exception as exc:
            failures.append(f"{item.name}: {exc}")
            print(f"FAILED: {item.name}: {exc}", file=sys.stderr)

    print()
    print(f"Completed: {created} created, {updated} updated, {len(failures)} failed.")
    if failures:
        for message in failures:
            print(f"  - {message}", file=sys.stderr)
        return 1
    return 0


def run_sync(*, dry_run: bool) -> int:
    metadata_records = build_metadata_records()
    branch = collect_git_branch()
    print(f"Repository: {REPO_ROOT}")
    print(f"Git branch: {branch}")
    print(f"Records: {len(metadata_records)}")

    try:
        api_key, database_id = validate_env(require_credentials=not dry_run)
    except EnvValidationError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if dry_run:
        planned = plan_sync_actions(metadata_records, {})
        print_planned_actions(planned, dry_run=True)
        print()
        print("Dry run complete. No Notion API calls were made.")
        return 0

    client = NotionSyncClient(api_key, database_id)
    try:
        existing_pages = index_pages_by_name(client.query_database_pages())
    except Exception as exc:
        print(f"ERROR: Could not query Notion database: {exc}", file=sys.stderr)
        return 1

    planned = plan_sync_actions(metadata_records, existing_pages)
    print_planned_actions(planned, dry_run=False)
    print()
    return execute_sync(client, planned)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync Career Evidence metadata/status to Notion (no file uploads).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned actions without calling the Notion API.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    raise SystemExit(run_sync(dry_run=args.dry_run))


if __name__ == "__main__":
    main()
