# Generated by Django 5.2.13 on 2026-05-09 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_starting', models.DateField()),
                ('week_ending', models.DateField()),
                ('target_applications', models.PositiveIntegerField(default=0)),
                ('actual_applications', models.PositiveIntegerField(default=0)),
                ('responses_received', models.PositiveIntegerField(default=0)),
                ('screening_calls', models.PositiveIntegerField(default=0)),
                ('technical_screens', models.PositiveIntegerField(default=0)),
                ('interviews', models.PositiveIntegerField(default=0)),
                ('offers', models.PositiveIntegerField(default=0)),
                ('rejections', models.PositiveIntegerField(default=0)),
                ('diagnosis', models.CharField(choices=[('low_activity', 'Low activity / consistency issue'), ('cv_targeting', 'CV / targeting issue'), ('messaging_fit', 'Messaging / role-fit issue'), ('screening', 'Screening-call issue'), ('interview', 'Interview performance issue'), ('strategy_working', 'Strategy working'), ('unknown', 'Unknown / not enough data')], default='unknown', max_length=40)),
                ('mood', models.CharField(choices=[('strong', 'Strong'), ('steady', 'Steady'), ('mixed', 'Mixed'), ('low', 'Low'), ('blocked', 'Blocked')], default='mixed', max_length=20)),
                ('what_worked', models.TextField(blank=True)),
                ('what_blocked', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('change_next_week', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly review',
                'verbose_name_plural': 'Weekly reviews',
                'ordering': ['-week_ending'],
                'unique_together': {('user', 'week_ending')},
            },
        ),
    ]
