# Generated by Django 5.2.13 on 2026-05-09 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_jobapplication_company_researched_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('stage', models.CharField(choices=[('screening', 'Screening call'), ('technical', 'Technical screen'), ('first', 'First interview'), ('final', 'Final interview'), ('task', 'Take-home / task')], default='screening', max_length=30)),
                ('outcome', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('passed', 'Passed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='scheduled', max_length=30)),
                ('interviewer_names', models.CharField(blank=True, max_length=240)),
                ('expected_topics', models.TextField(blank=True)),
                ('projects_to_mention', models.TextField(blank=True)),
                ('questions_to_prepare', models.TextField(blank=True)),
                ('profile_answer_prepared', models.BooleanField(default=False)),
                ('company_answer_prepared', models.BooleanField(default=False)),
                ('project_walkthrough_prepared', models.BooleanField(default=False)),
                ('sql_practice_done', models.BooleanField(default=False)),
                ('python_practice_done', models.BooleanField(default=False)),
                ('star_examples_prepared', models.BooleanField(default=False)),
                ('questions_for_employer_prepared', models.BooleanField(default=False)),
                ('reflection', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_preps', to='applications.jobapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_preps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['interview_date', 'created_at'],
            },
        ),
    ]
